name: Major.Minor.Fix.Build

on:
  push:
    branches:
    - master
    #- 'release/Major.Minor.Fix.Build'
    #- 'hotfix/Major.Minor.Fix.Build'


jobs:
  build-project:
    name: Build project
    runs-on: windows-latest
    steps:
    - id: build_project
    - name: Check the code
      uses: actions/checkout@v3

    - name: Add MSbuild to path
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Restore NuGet
      run: nuget restore JSImpl/solution/JSImpl.sln

    - name: Build Solution
      run: msbuild -m JSImpl/solution/JSImpl.sln
    # Uploading test.exe into artifacts
    - name: Upload test.exe
      uses: actions/upload-artifact@v3
      with:
        name: test
        path: JSImpl/build/bin/Debug/Test.exe
    # Uploading JSImpl.exe into artifacts
    - name: Upload JSImpl.exe
      uses: actions/upload-artifact@v3
      with:
        name: JSImpl
        path: JSImpl/build/bin/Debug/JSImpl.exe
    # Uploading dummy_gc.exe into artifacts
    - name: Upload dummy_gc.exe
      uses: actions/upload-artifact@v3
      with:
        name: dummy_gc
        path: JSImpl/build/bin/Debug/dummy_gc.exe
    # Uploading spasm.exe into artifacts
    - name: Upload spasm.exe
      uses: actions/upload-artifact@v3
      with:
        name: spasm
        path: JSImpl/build/bin/Debug/spasm.exe

  release-project:
   name: Release project
   runs-on: windows-latest
   needs: build-project
   steps:
    - id: release_project
    # Downloading test.exe from artifacts
    - name: Download test.exe
      uses: actions/download-artifact@v3
      with:
        name: test
    # Downloading JSImpl.exe from artifacts
    - name: Download JSImpl.exe
      uses: actions/download-artifact@v3
      with:
        name: JSImpl
    # Downloading dummy_gc.exe from artifacts
    - name: Download dummy_gc.exe
      uses: actions/download-artifact@v3
      with:
        name: dummy_gc
    # Downloading spasm.exe from artifacts
    - name: Download spasm.exe
      uses: actions/download-artifact@v3
      with:
        name: spasm
    - name: Archive items
      uses: thedoctor0/zip-release@master
      with:
        filename: 'items.zip'
        path: .
          #JSImpl/build/bin/Debug/spasm.exe
  #merge-project:
  #  name: Merge to master
  #  runs-on: windows-latest
  #  steps:
  #  - name: merge to master
    #if: steps.build_project.outcome == 'success'
  #    if: ${{ (steps.release_project.outcome == 'success') && (steps.build_project.outcome == 'success') }}
      #uses: mtanzi/action-automerge@v1
      #id: merge
      #with:
      #  github_token: ${{ github.token }}
      #  source: 'release/Major.Minor.Fix.Build'
      #  target: 'master'
        #webhook_url: #if present add the Slack webhook


    