name: Build&Test

on:
  push:
    branches:
    - 'release/Major.Minor.Fix.Build'
    - 'hotfix/Major.Minor.Fix.Build'


jobs:
  build-project:
    name: Build project

    runs-on: windows-latest

    steps:
    - name: Check the code
      uses: actions/checkout@v3

    - name: Adding NPM and NodeJS
      run: npm install

    - name: Add MSbuild to path
      uses: microsoft/setup-msbuild@v1.1

    - name: Build app for Release
      run: npm run build
    - name: Upload content
      uses: actions/upload-artifact@v3
      with:
        name: simple-project
        path: .