name: Build&Test

on:
  push:
    branches:
    - master
    #- 'release/Major.Minor.Fix.Build'
    #- 'hotfix/Major.Minor.Fix.Build'


jobs:
  build-project:
    name: Build project

    runs-on: windows-latest

    steps:
    - name: Check the code
      uses: actions/checkout@v3

    - name: Add MSbuild to path
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Restore NuGet
      run: nuget restore JSImpl/solution/JSImpl.sln

    - name: Build Solution
      run: msbuild JSImpl/solution/JSImpl.sln